# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mayastorCP:
  registry:
  pullPolicy: Always
  logLevel: info

mspRequests:
  cpu: "250m"
  memory: "500Mi"

mspLimits:
  cpu: "1000m"
  memory: "1Gi"
