[profile.dev]
panic = "abort"

[workspace]
members = [
	"jsonrpc",
	"libnvme-rs",
	"io-engine",
    "io-engine-bench",
	"rpc",
	"sysfs",
	"composer",
	"spdk-rs",
	"utils/io-engine-dependencies/version-info",
]
