[patch.crates-io]
rpc = { git = "https://github.com/openebs/mayastor", rev = "5b4d4726190e176ba006c78582aa3fea5ac3ceb6" }

[workspace]

members = [
    "control-plane/agents",
    "control-plane/mbus-api",
    "composer",
    "control-plane/rest",
    "control-plane/macros",
    "control-plane/deployer",
# Test mayastor through the rest api
    "tests-mayastor",
]
