apiVersion: apps/v1
kind: Deployment
metadata:
  name: msp-operator
  namespace: mayastor
  labels:
    app: msp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msp-operator
  template:
    metadata:
      labels:
        app: msp-operator
    spec:
      serviceAccount: mayastor-service-account
      containers:
        - name: msp-operator
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          image: {{ .Values.mayastorCP.registry }}mayadata/mcp-msp-operator:{{ .Values.mayastorCP.tag}}
          imagePullPolicy: {{ .Values.mayastorCP.pullPolicy }}
          args:
            - "-e http://$(REST_SERVICE_HOST):8081"
          env:
            - name: RUST_LOG
              value: info,msp_operator={{ .Values.mayastorCP.logLevel }}
      imagePullSecrets:
        - name: regcred
