[package]
name = "openapi"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = { version = "^2.2", features = ["serde"] }
async-trait = "0.1.42"
dyn-clonable = "0.9.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
actix-web = { version = "4.0.0-beta.8", features = ["rustls"] }
actix-web-opentelemetry = { git = "https://github.com/fourbs-net/actix-web-opentelemetry" }
awc = "3.0.0-beta.7"
serde_urlencoded = "0.7"
rustls = "0.19.1"