[package]
name = "openapi"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = { version = "^2.2", features = ["serde"] }
async-trait = "0.1.42"
uuid = { version = "0.8", features = ["serde", "v4"] }
actix-web = { version = "4.0.0-beta.8", features = ["rustls"] }