[package]
name = "rest"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rest"
path = "./service/src/main.rs"

[lib]
name = "rest_client"
path = "./src/lib.rs"

[dependencies]
# Actix Server, Client and telemetry
rustls = "0.19.1"
actix-web = { version = "4.0.0-beta.8", features = ["rustls"] }
actix-service = "2.0.0"
opentelemetry-jaeger = { version = "0.14", features = ["tokio"] }
tracing-opentelemetry = "0.14.0"
opentelemetry = "0.15.0"
actix-web-opentelemetry = "0.11.0-beta.4"
actix-http = "3.0.0-beta.8"
awc = "3.0.0-beta.7"

async-trait = "=0.1.42"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml = "0.8.17"
structopt = "0.3.15"
futures = "0.3.8"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
strum = "0.19"
strum_macros = "0.19"
anyhow = "1.0.32"
snafu = "0.6"
url = "2.2.0"
http = "0.2.3"
tinytemplate = { version = "1.2" }
jsonwebtoken = "7.2.0"
composer = { path = "../../composer" }
common-lib = { path = "../../common" }

[dev-dependencies]
rpc = { path = "../../rpc"}
tokio = { version = "1", features = ["full"] }
actix-rt = "2.2.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
