[package]
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
edition = "2018"
name = "jsonrpc"
version = "0.1.0"

[dependencies]
futures = "0.1.25"
log = "0.4"
nix = "0.14.1"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.36"
tokio = "0.1.18"
tokio-threadpool = "*"
tower-grpc = "0.1.0"
